# Generated by Django 5.2.5 on 2025-08-21 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zhuye', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uprofile',
            name='avatar',
            field=models.ImageField(default='/avatars/default_avatar.png', upload_to='avatars/', verbose_name='头像'),
        ),
    ]
